apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dmonster
spec:
  project: service-app
  source:
    repoURL: 'git@github.com:castellabakery/disease_monster.git'
    path: manifests/disease_monster
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dmonster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true