apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personality
spec:
  project: service-app
  source:
    repoURL: 'git@github.com:castellabakery/personality.git'
    path: manifests/personality
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: personality
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true