apiVersion: v1
kind: Service
metadata:
  name: scouter-client-svc
spec:
  type: ClusterIP
  selector:
    app: scouter-client
  ports:
    - name: client
      protocol: TCP
      port: 8080
      targetPort: 80
