alertmanager:
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  servicePort: 80
  nodePort: 30115
  sessionAffinity: None
  type: NodePort


server:
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  servicePort: 80
  sessionAffinity: None
  type: NodePort
  nodePort: 30116