apiVersion: v1
description: High Performance, Kubernetes Native Object Storage
name: minio
version: 8.0.10
appVersion: RELEASE.2021-02-14T04-01-33Z
keywords:
- storage
- object-storage
- S3
home: https://min.io
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
- https://github.com/minio/minio
maintainers:
- name: MinIO, Inc
  email: dev@minio.io
