apiVersion: apps/v1
kind: Deployment
metadata:
 name: minio
 namespace: {{ .Values.namespace }}
 labels:
  app: minio
spec:
 replicas: 1
 selector:
  matchLabels:
   app: minio
 template:
  metadata:
   labels:
    app: minio
  spec:
   containers:
   - name: minio
     image: {{ .Values.imageRegistry }}/minio/minio:{{ .Values.moduleVersion.minio }}
     imagePullPolicy: Always
     command: ['bash', '-c']
     args: ['minio server /data --console-address :9091 --address :9090']
     env:
     - name: MINIO_ROOT_USER
       value: {{ .Values.MINIO_ROOT_USER }}
     - name: MINIO_ROOT_PASSWORD
       value: {{ .Values.MINIO_ROOT_PASSWORD }}
     ports:
     - name: service-minio
       containerPort: 9090
     - name: web-minio
       containerPort: 9091
     volumeMounts:
     - name: minio-vol
       mountPath: /data
   volumes:
   - name: minio-vol
     hostPath:
      path: /data/minio
      type: DirectoryOrCreate
