apiVersion: apps/v1
kind: Deployment
metadata:
  name: scouter-collector
  labels:
    app: scouter-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scouter-collector
  template:
    metadata:
      labels:
        app: scouter-collector
    spec:
      containers:
        - name: scouter-collector
          image: docker.io/scouterapm/scouter-server:2.17.1
          imagePullPolicy: Always
          env:
            - name: SC_SERVER_ID
              value: "SCCOUTER-COLLECTOR"
            - name: NET_HTTP_SERVER_ENABLED
              value: "true"
            - name: NET_HTTP_API_SWAGGER_ENABLED
              value: "true"
            - name: NET_HTTP_API_ENABLED
              value: "true"
            - name: MGR_PURGE_PROFILE_KEEP_DAYS
              value: "2"
            - name: MGR_PURGE_XLOG_KEEP_DAYS
              value: "5"
            - name: MGR_PURGE_COUNTER_KEEP_DAYS
              value: "15"
            - name: JAVA_OPT
              value: "-Xms1024m -Xmx1024m"
          ports:
            - name: collector
              containerPort: 6100
              protocol: UDP
            - name: api
              containerPort: 6180
          volumeMounts:
            - name: scouter-collector-logs
              mountPath: /home/scouter-server/logs
            - name: scouter-collector-database
              mountPath: /home/scouter-server/database
      volumes:
        - name: scouter-collector-logs
          hostPath:
            path: /data/scouter/logs
            type: DirectoryOrCreate
        - name: scouter-collector-database
          hostPath:
            path: /data/scouter/database
            type: DirectoryOrCreate
