apiVersion: v1
kind: Service
metadata:
  name: scouter-collector-svc
spec:
  type: ClusterIP
  selector:
    app: scouter-collector
  ports:
    - name: collect
      protocol: UDP
      port: 6100
      targetPort: 6100
    - name: api
      protocol: TCP
      port: 6180
      targetPort: 6180