apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-replica1-pv
spec:
  storageClassName: minio-storage
  capacity:
    storage: {{ .Values.replica1.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.replica1.persistence.hostPath }}
    type: DirectoryOrCreate