apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager-pv
spec:
  storageClassName: prometheus-alertmanager-storage
  capacity:
    storage: {{ .Values.alertmanager.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.alertmanager.persistence.hostPath }}
    type: DirectoryOrCreate