apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  storageClassName: prometheus-storage
  capacity:
    storage: {{ .Values.server.persistentVolume.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.server.persistentVolume.hostPath }}
    type: DirectoryOrCreate