apiVersion: v1
kind: Service
metadata:
  name: mariadb-external-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - nodePort: {{ .Values.port }}
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql
  type: NodePort