apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  storageClassName: prometheus-storage
  capacity:
    storage: {{ .Values.prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/prometheus
    type: DirectoryOrCreate