apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploytest
spec:
  project: service-app
  source:
    repoURL: 'https://github.com/castellabakery/deploytest.git'
    path: manifests/deploytest
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: deploytest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true