apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: healer
spec:
  project: service-app
  source:
    repoURL: 'git@github.com:castellabakery/healer.git'
    path: manifests/healer
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: healer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true