apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
spec:
  project: common
  source:
    repoURL: 'https://github.com/castellabakery/manifests.git'
    path: manifests/nfs-subdir-external-provisioner/charts
    targetRevision: main
    helm:
      parameters:
        - name: 'nfs.mountOptions[0]'
          value: nfsvers=3
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true