apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kafka-cont
provisioner: cluster.local/nfs-provisioner-nfs-subdir-external-provisioner
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate