apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    app.kubernetes.io/name: "ingress-nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    cert-manager.io/cluster-issuer: {{ .Values.secretName }}
spec:
  tls:
    - hosts:
        - "{{ .Values.subDomain }}.{{ .Values.domain }}"
      secretName: {{ .Values.secretName }}
  rules:
    - host: "{{ .Values.subDomain }}.{{ .Values.domain }}"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080