apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akhq
spec:
  project: monitor
  source:
    repoURL: 'https://github.com/castellabakery/manifests.git'
    path: manifests/akhq/charts
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: akhq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true