apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: balpum
spec:
  project: service-app
  source:
    repoURL: 'https://github.com/chunyul0504/balpum.git'
    path: manifests/chart
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: balpum
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true