apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
spec:
  project: common
  source:
    repoURL: 'https://github.com/castellabakery/manifests.git'
    path: manifests/keycloak/simple/charts
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true