apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsencrypt
spec:
  project: common
  source:
    repoURL: 'https://github.com/castellabakery/manifests.git'
    path: manifests/letsencrypt/charts
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true