apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: serialfactory
spec:
  project: service-app
  source:
    repoURL: 'git@github.com:castellabakery/serialfactory.git'
    path: manifests/serialfactory
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: serialfactory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true