apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simulator
spec:
  project: service-app
  source:
    repoURL: 'git@github.com:castellabakery/simulator.git'
    path: manifests/simulator
    targetRevision: master
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: simulator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true