apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
spec:
  project: common
  source:
    repoURL: 'https://github.com/castellabakery/manifests.git'
    path: manifests/kafka/charts
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true