apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
spec:
  project: common
  source:
    repoURL: 'https://github.com/castellabakery/manifests.git'
    path: manifests/nexus-repository-manager/charts
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nexus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true