apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mariadb-storage
provisioner: kubernetes.io/no-provisioner
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mariadb-storage1
provisioner: kubernetes.io/no-provisioner
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate