apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pc-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: prod
            url: 'https://kubernetes.default.svc'
  template:
    metadata:
      name: '{{cluster}}-settings'
    spec:
      project: default
      source:
        repoURL: https://github.com/castellabakery/manifests.git
        targetRevision: main
        path: applicationset/list/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: argocd