apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consumebatch
spec:
  project: service-app
  source:
    repoURL: 'git@github.com:castellabakery/consumeBatch.git'
    path: manifests/chart
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: consumebatch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true