apiVersion: v1
kind: Service
metadata:
 name: minio
 namespace: {{ .Values.namespace }}
spec:
 type: NodePort
 selector:
  app: minio
 ports:
 - name: web-minio
   #protocol: TCP
   port: 9091
   targetPort: 9091
   nodePort: 30091
 - name: service-minio
   #protocol: TCP
   port: 9090
   targetPort: 9090
   nodePort: 30090
